services:
  extractor:
    build:
      context: .
      dockerfile: dockerfile
    container_name: extractor
    restart: unless-stopped
    environment:
      - SQLITE_PATH=/app/data/db.sqlite3
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data: